[package]
name = "sakaya"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
notify-rust = "4.8.0"
reqwest = { version = "0.11.18", features = ["json", "blocking"] }
