.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH sakaya 1  "sakaya 0.1.0" 
.SH NAME
sakaya \- Run native wine applications inside declarative systemd\-nspawn containers.
.SH SYNOPSIS
\fBsakaya\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fIEXECUTABLE\fR] 
.SH DESCRIPTION
Run native wine applications inside declarative systemd\-nspawn containers.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.TP
[\fIEXECUTABLE\fR] [default: ]
Path to the executable to run
.SH VERSION
v0.1.0
.SH AUTHORS
Donovan Glover
