.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH sakaya 1  "sakaya 0.1.0" 
.SH NAME
sakaya \- Run native wine applications inside declarative systemd\-nspawn containers.
.SH SYNOPSIS
\fBsakaya\fR [\fB\-a\fR|\fB\-\-address\fR] [\fB\-s\fR|\fB\-\-server\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fIFILE\fR] 
.SH DESCRIPTION
Run native wine applications inside declarative systemd\-nspawn containers.
.SH OPTIONS
.TP
\fB\-a\fR, \fB\-\-address\fR=\fIADDRESS\fR [default: 192.168.100.49:39493]
Address
.TP
\fB\-s\fR, \fB\-\-server\fR
Start a server instead of a client
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.TP
[\fIFILE\fR]
Path to the executable to run
.SH VERSION
v0.1.0
.SH AUTHORS
Copyright (C) 2023 Donovan Glover <https://donovan.is/>
