[package]
name = "sakaya"
description = "Run native wine applications inside declarative systemd-nspawn containers."
version = "0.1.0"
authors = ["Copyright (C) 2023 Donovan Glover <https://donovan.is/>"]
repository = "https://github.com/donovanglover/sakaya"
license = "MIT"
edition = "2021"

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
home = "0.5.5"
ico = "0.3.0"
pelite = "0.10.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7.6"

[build-dependencies]
clap = { version = "4.3.19", features = ["derive"] }
clap_complete = "4.3.2"
clap_mangen = "0.2.12"

[dev-dependencies]
assert_cmd = "2.0.12"
rustympkglib = "0.1.1"
