[package]
name = "sakaya-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gio = "0.17.10"
gtk = "0.17.1"
gtk-layer-shell = "0.6.1"
